### PR TITLE
typofixes

### PR DESCRIPTION
**Pull request by mLuby**
Fantastic post—looking forward to part 2!

### CODE REVIEW

**Comment by tedkornish** [comment]
While this is up, there's one more typo I noticed — the sentence "It’s kind is * -> *." should be changed to "Its kind is * -> *."

**Comment by mLuby** [comment]
Nice catch @tedkornish ; I added that to this commit.

**Comment by slpopejoy** [comment]
Thanks for the edits! This site is generated from https://github.com/slpopejoy/tatterdemalion/ so I manually applied your fixes there. I've also added automatic literate source links and updated the readme for future editors.

Cheers,
Stuart

**Comment by slpopejoy** [comment]
Oh and you know part 2 is already there right? :) https://slpopejoy.github.io/posts/Effectful02.html

Related commit in the other project: https://github.com/slpopejoy/tatterdemalion/commit/98e39d8695ab8d4b090cc44758e60ab358bba0ff

**Pull request closed without merging**
